server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smartdocs}
spring.datasource.username=${DB_USERNAME:smartdocs}
spring.datasource.password=${DB_PASSWORD:smartdocs123}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

jwt.secret=${JWT_SECRET:dev-only-secret-never-use-this-value-in-prod-32bytes}
jwt.expiration-ms=86400000

groq.api.key=${GROQ_API_KEY:gsk-placeholder}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=${GROQ_MODEL:llama-3.3-70b-versatile}
groq.max-tokens=2048

smartdocs.storage.path=./uploads
smartdocs.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:80,http://localhost:3000}

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}
spring.rabbitmq.username=${RABBITMQ_USERNAME:smartdocs}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:smartdocs123}

smartdocs.rabbitmq.exchange=document.exchange
smartdocs.rabbitmq.queue=document.processing.queue
smartdocs.rabbitmq.routing-key=document.processing

smartdocs.rabbitmq.dlx-exchange=document.exchange.dlx
smartdocs.rabbitmq.dlq=document.processing.dlq
smartdocs.rabbitmq.dlq-routing-key=document.processing.dlq

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=4
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000